#### https://www.notion.so/332f76ee7f8680e5b459ea9e58da4e7f?v=332f76ee7f8680f0a330000c3e536d51&source=copy_link

### Get pages by database ID
@databaseId = 332f76ee7f8680e5b459ea9e58da4e7f
@baseurl = http://localhost:3500

### Get pages by database ID
GET {{baseurl}}/api/databases/{{databaseId}}/pages HTTP/1.1
Content-Type: application/json

### Get pages by database ID with pagination

GET {{baseurl}}/api/databases/{{databaseId}}/pages?prefix=aws HTTP/1.1
Content-Type: application/json


### Get pages by database ID with pagination

GET {{baseurl}}/api/databases/{{databaseId}}/pages?page=3&pageSize=10 HTTP/1.1
Content-Type: application/json